name: tamannaah
description: Tamannaah
version: 0.0.31
homepage: https://github.com/WitchOfDark/Witches/tree/main/packages/Tamannaah

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  intl: ^0.17.0

  go_router: ^6.0.3

  flutter_form_builder: ^7.7.0
  flutter_typeahead: ^4.3.1
  sleek_circular_slider: ^2.0.1
  scrollable_positioned_list: ^0.3.5

  flutter_screenutil: ^5.6.0
  device_preview: ^1.1.0
  device_preview_screenshot: ^1.0.0

  flutter_animate: ^3.0.0

  url_launcher: ^6.1.10
  cached_network_image: ^3.2.3
  flutter_blurhash: ^0.7.0

  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  bloc: ^8.1.1
  provider: ^6.0.5
  http: ^0.13.5
  stack_trace: ^1.11.0
  rxdart: ^0.27.7
  crypto: ^3.0.2

  ######
  pluto_grid: ^5.4.9
  ######

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
