name: tamannaah
description: Tamannaah
version: 0.0.2
homepage: https://github.com/WitchOfDark/Tamannaah

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0

  rxdart: ^0.27.7

  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  equatable: ^2.0.5

  hive: ^2.2.3
  isar: ^3.0.2
  isar_flutter_libs: ^3.0.2

  # dio: ^4.0.6
  http: ^0.13.5

  crypto: ^3.0.2
  path: ^1.8.2
  path_provider: ^2.0.11

  stack_trace: ^1.10.0

  go_router: ^6.0.0

  flutter_form_builder: ^7.7.0
  flutter_typeahead: ^4.3.1
  sleek_circular_slider: ^2.0.1
  pluto_grid: ^5.4.9

  google_fonts: ^4.0.1

  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  firebase_ui_auth: ^1.1.6
  cloud_firestore: ^4.0.3
  firebase_storage: ^11.0.8
  firebase_app_check: ^0.1.1+6
  google_sign_in: ^5.4.2

  flutter_screenutil: ^5.6.0
  device_preview: ^1.1.0
  device_preview_screenshot: ^1.0.0

  # flutter_appauth: ^4.2.0

  # flutter_secure_storage: ^6.0.0

  url_launcher: ^6.1.7

  flutter_animate: ^3.0.0

  cached_network_image: ^3.2.3
  flutter_blurhash: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  hive_generator: ^1.1.3
  isar_generator: ^3.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
