name: inferno
description: Inferno
version: 0.0.1
homepage: https://github.com/WitchOfDark/Witches/tree/main/packages/Inferno

publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^4.1.0

  # firebase_ui_auth: ^1.1.6

  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  equatable: ^2.0.5

  tamannaah:
    path: ../Tamannaah

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
