name: miner
description: Miner
version: 0.0.1
homepage: https://github.com/WitchOfDark/Witches/tree/main/packages/Miner

publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.2
  path_provider: ^2.0.12
  hive: ^2.2.3

  tamannaah: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.3.3
  hive_generator: ^1.1.3
  isar_generator: ^3.0.2

flutter:
